### ISSUE TITLE
Cannot use datadog-lambda-js with Webpack

### ISSUE THREAD

**Issue by sime** [DataDog/datadog-lambda-layer-js#30]
## Expected Behavior

Bundling datadog-lambda-js works.

## Actual Behavior

Unable to build bundle with serverless-webpack

## Steps to Reproduce the Problem

```shell
$ sls create -t aws-nodejs-ecma-script -p dd-webpack
$ cd dd-webpack/
$ yarn add datadog-lambda-js
$ sed -i '1s/^/const { datadog } = require("datadog-lambda-js");\n/' first.js # Add library to beginning of file
$ sls package
``` 

## Specifications

  - Datadog Lambda Layer version: v0.5
  - Node version: 8.16.0
  
## Stacktrace
  
  ```
Serverless: Bundling with Webpack...
Time: 2821ms
Built at: 2019-10-24 18:12:00
    Asset      Size  Chunks             Chunk Names
 first.js  7.84 MiB   first  [emitted]  first
second.js  4.42 KiB  second  [emitted]  second
Entrypoint first = first.js
Entrypoint second = second.js
[./first.js] 374 bytes {first} [built]
[./node_modules/aws-sdk/lib/aws.js] 159 bytes {first} [optional] [built]
[./node_modules/datadog-lambda-js/dist/index.js] 9.99 KiB {first} [built]
[./node_modules/datadog-lambda-js/dist/metrics/api.js] 2.51 KiB {first} [built]
[./node_modules/datadog-lambda-js/dist/metrics/index.js] 297 bytes {first} [built]
[./node_modules/datadog-lambda-js/dist/metrics/kms-service.js] 4.33 KiB {first} [built]
[./node_modules/datadog-lambda-js/dist/metrics/listener.js] 8.94 KiB {first} [built]
[./node_modules/datadog-lambda-js/dist/metrics/model.js] 2.38 KiB {first} [built]
[./node_modules/datadog-lambda-js/dist/trace/index.js] 200 bytes {first} [built]
[./node_modules/datadog-lambda-js/dist/trace/listener.js] 4.83 KiB {first} [built]
[./node_modules/datadog-lambda-js/dist/utils/handler.js] 5.35 KiB {first} [built]
[./node_modules/datadog-lambda-js/dist/utils/index.js] 420 bytes {first} [built]
[./node_modules/datadog-lambda-js/dist/utils/log.js] 1.63 KiB {first} [built]
[./node_modules/datadog-lambda-js/dist/utils/timer.js] 2.52 KiB {first} [built]
[./second.js] 411 bytes {second} [built]
    + 1153 hidden modules

WARNING in ./node_modules/dd-trace/packages/dd-trace/src/platform/node/loader.js 143:11-31
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/dd-trace/packages/dd-trace/src/platform/node/index.js
 @ ./node_modules/dd-trace/packages/dd-trace/index.js
 @ ./node_modules/dd-trace/index.js
 @ ./node_modules/datadog-lambda-js/dist/trace/listener.js
 @ ./node_modules/datadog-lambda-js/dist/trace/index.js
 @ ./node_modules/datadog-lambda-js/dist/index.js
 @ ./first.js

WARNING in ./node_modules/colors/lib/colors.js 127:29-43
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/colors/safe.js
 @ ./node_modules/winston/lib/winston/config.js
 @ ./node_modules/winston/lib/winston.js
 @ ./node_modules/aws-xray-sdk-core/lib/logger.js
 @ ./node_modules/aws-xray-sdk-core/lib/context_utils.js
 @ ./node_modules/aws-xray-sdk-core/lib/aws-xray.js
 @ ./node_modules/aws-xray-sdk-core/lib/index.js
 @ ./node_modules/datadog-lambda-js/dist/trace/context.js
 @ ./node_modules/datadog-lambda-js/dist/trace/listener.js
 @ ./node_modules/datadog-lambda-js/dist/trace/index.js
 @ ./node_modules/datadog-lambda-js/dist/index.js
 @ ./first.js

ERROR in ./node_modules/dd-trace/packages/datadog-plugin-graphql/src/tools/transforms.js
Module not found: Error: Can't resolve 'graphql/language/printer' in '/private/tmp/dd-webpack/node_modules/dd-trace/packages/datadog-plugin-graphql/src/tools'
 @ ./node_modules/dd-trace/packages/datadog-plugin-graphql/src/tools/transforms.js 10:18-53
 @ ./node_modules/dd-trace/packages/datadog-plugin-graphql/src/tools/signature.js
 @ ./node_modules/dd-trace/packages/datadog-plugin-graphql/src/tools/index.js
 @ ./node_modules/dd-trace/packages/datadog-plugin-graphql/src/index.js
 @ ./node_modules/dd-trace/packages/dd-trace/src/plugins/index.js
 @ ./node_modules/dd-trace/packages/dd-trace/src/platform/node/index.js
 @ ./node_modules/dd-trace/packages/dd-trace/index.js
 @ ./node_modules/dd-trace/index.js
 @ ./node_modules/datadog-lambda-js/dist/trace/listener.js
 @ ./node_modules/datadog-lambda-js/dist/trace/index.js
 @ ./node_modules/datadog-lambda-js/dist/index.js
 @ ./first.js

ERROR in ./node_modules/dd-trace/packages/datadog-plugin-graphql/src/tools/transforms.js
Module not found: Error: Can't resolve 'graphql/language/visitor' in '/private/tmp/dd-webpack/node_modules/dd-trace/packages/datadog-plugin-graphql/src/tools'
 @ ./node_modules/dd-trace/packages/datadog-plugin-graphql/src/tools/transforms.js 9:18-53
 @ ./node_modules/dd-trace/packages/datadog-plugin-graphql/src/tools/signature.js
 @ ./node_modules/dd-trace/packages/datadog-plugin-graphql/src/tools/index.js
 @ ./node_modules/dd-trace/packages/datadog-plugin-graphql/src/index.js
 @ ./node_modules/dd-trace/packages/dd-trace/src/plugins/index.js
 @ ./node_modules/dd-trace/packages/dd-trace/src/platform/node/index.js
 @ ./node_modules/dd-trace/packages/dd-trace/index.js
 @ ./node_modules/dd-trace/index.js
 @ ./node_modules/datadog-lambda-js/dist/trace/listener.js
 @ ./node_modules/datadog-lambda-js/dist/trace/index.js
 @ ./node_modules/datadog-lambda-js/dist/index.js
 @ ./first.js

ERROR in ./node_modules/dd-trace/packages/datadog-plugin-graphql/src/tools/transforms.js
Module not found: Error: Can't resolve 'graphql/utilities' in '/private/tmp/dd-webpack/node_modules/dd-trace/packages/datadog-plugin-graphql/src/tools'
 @ ./node_modules/dd-trace/packages/datadog-plugin-graphql/src/tools/transforms.js 11:20-48
 @ ./node_modules/dd-trace/packages/datadog-plugin-graphql/src/tools/signature.js
 @ ./node_modules/dd-trace/packages/datadog-plugin-graphql/src/tools/index.js
 @ ./node_modules/dd-trace/packages/datadog-plugin-graphql/src/index.js
 @ ./node_modules/dd-trace/packages/dd-trace/src/plugins/index.js
 @ ./node_modules/dd-trace/packages/dd-trace/src/platform/node/index.js
 @ ./node_modules/dd-trace/packages/dd-trace/index.js
 @ ./node_modules/dd-trace/index.js
 @ ./node_modules/datadog-lambda-js/dist/trace/listener.js
 @ ./node_modules/datadog-lambda-js/dist/trace/index.js
 @ ./node_modules/datadog-lambda-js/dist/index.js
 @ ./first.js

  Error --------------------------------------------------

  Error: Webpack compilation error, see above
      at _.forEach.compileStats (/private/tmp/dd-webpack/node_modules/serverless-webpack/lib/compile.js:38:19)
      at arrayEach (/private/tmp/dd-webpack/node_modules/lodash/lodash.js:516:11)
      at Function.forEach (/private/tmp/dd-webpack/node_modules/lodash/lodash.js:9342:14)
      at BbPromise.fromCallback.then.stats (/private/tmp/dd-webpack/node_modules/serverless-webpack/lib/compile.js:31:11)
      at tryCatcher (/private/tmp/dd-webpack/node_modules/bluebird/js/release/util.js:16:23)
      at Promise._settlePromiseFromHandler (/private/tmp/dd-webpack/node_modules/bluebird/js/release/promise.js:547:31)
      at Promise._settlePromise (/private/tmp/dd-webpack/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/private/tmp/dd-webpack/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/private/tmp/dd-webpack/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/private/tmp/dd-webpack/node_modules/bluebird/js/release/promise.js:673:18)
      at /private/tmp/dd-webpack/node_modules/bluebird/js/release/nodeback.js:42:21
      at finalCallback (/private/tmp/dd-webpack/node_modules/webpack/lib/Compiler.js:257:39)
      at hooks.done.callAsync.err (/private/tmp/dd-webpack/node_modules/webpack/lib/Compiler.js:306:14)
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/private/tmp/dd-webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (/private/tmp/dd-webpack/node_modules/tapable/lib/Hook.js:154:20)
      at emitRecords.err (/private/tmp/dd-webpack/node_modules/webpack/lib/Compiler.js:304:22)
      at Compiler.emitRecords (/private/tmp/dd-webpack/node_modules/webpack/lib/Compiler.js:499:39)
      at emitAssets.err (/private/tmp/dd-webpack/node_modules/webpack/lib/Compiler.js:298:10)
      at hooks.afterEmit.callAsync.err (/private/tmp/dd-webpack/node_modules/webpack/lib/Compiler.js:485:14)
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/private/tmp/dd-webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at AsyncSeriesHook.lazyCompileHook (/private/tmp/dd-webpack/node_modules/tapable/lib/Hook.js:154:20)
      at asyncLib.forEachLimit.err (/private/tmp/dd-webpack/node_modules/webpack/lib/Compiler.js:482:27)
      at /private/tmp/dd-webpack/node_modules/neo-async/async.js:2818:7
      at done (/private/tmp/dd-webpack/node_modules/neo-async/async.js:3522:9)
      at AsyncSeriesHook.eval [as callAsync] (eval at create (/private/tmp/dd-webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
      at outputFileSystem.writeFile.err (/private/tmp/dd-webpack/node_modules/webpack/lib/Compiler.js:464:33)
      at /Users/simon.males/.npm-packages/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:111:16
      at /private/tmp/dd-webpack/node_modules/graceful-fs/graceful-fs.js:57:14
      at /Users/simon.males/.npm-packages/lib/node_modules/serverless/node_modules/graceful-fs/graceful-fs.js:45:10
      at FSReqWrap.oncomplete (fs.js:135:15)

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              8.16.0
     Framework Version:         1.55.1
     Plugin Version:            3.2.0
     SDK Version:               2.1.2
     Components Core Version:   1.1.2
     Components CLI Version:    1.4.0  ```

**Comment by sime** [comment]
It _might_ be related to this: https://github.com/DataDog/dd-trace-js/issues/652

**Comment by DarcyRaynerDD** [comment]
Hey sime, thanks for the detailed report. I actually think this is a problem with the graphql plugin in dd-trace-js. I modified my local node_modules to remove that plugin, and any references to it, and was able to package the function, (although still with some warnings related to the x-ray sdk). It looks like the plugin is doing some dynamic importing of graphql libraries. We might be able to fix that so dd-trace-js is webpackable, (although the graph ql plugin likely wouldn't work). Like you pointed out though, dd-trace-js in general relies on being able to hook into node's require system, so auto instrumentation won't work with webpacking.

Some potential fixes to try in the interim:
- marking graphql as [external in your webpack config](https://webpack.js.org/configuration/externals/)
- marking datadog-lambda as external, and then attaching our lambda layer to your function, (you may still need a local copy as a development dependency for type information)

**Comment by DarcyRaynerDD** [comment]
Hi @sime. I've tested this with a recent version of the tracer and dd-lambda-layer-js, and was able to use webpacking with this library. We've made dd-trace-js an optional dependency of the npm package, (although it is still included in the lambda layer by default). Feel free to reopen this issue if you run into any other trouble with webpacking.

**Comment by gaiachik** [comment]
Hi. I am getting exactly the same issue as the first post when webpack builds...

### Specs
Datadog Lambda Layer version: v0.5 `"datadog-lambda-js": "^2.23.0",`
Node version: nodejs10.x
DD tracer version: `"dd-trace": "^0.20.1",`
serverless-webpack 5.3.1
webpack 4.42.1

**Comment by DarcyRaynerDD** [comment]
Hi @gaiachik. Do you think you would be able to share a sample repository which reproduces the issue? It would really help us narrow this down. As a workaround, have you tried using [serverless-plugin-datadog](https://github.com/DataDog/serverless-plugin-datadog#how-do-i-use-this-with-serverless-webpack), with the addLayers option set to true?

**Comment by gaiachik** [comment]
> Hi @gaiachik. Do you think you would be able to share a sample repository which reproduces the issue? It would really help us narrow this down. As a workaround, have you tried using [serverless-plugin-datadog](https://github.com/DataDog/serverless-plugin-datadog#how-do-i-use-this-with-serverless-webpack), with the addLayers option set to true?

I am SORRY. I had completely missed the bit about putting the `serverless-plugin-datadog` _before_ the `serverless-webpack`. that fixed it. sorry for the bother!

**Comment by DarcyRaynerDD** [comment]
@gaiachik No worries. It's good to hear you've found the problem.
