### ISSUE TITLE
Cannot find redirected handler

### ISSUE THREAD

**Issue by MxKaras** [DataDog/datadog-lambda-layer-js#77]
## Expected Behavior

Adding the layer to my lambda, setting up the required environment variables, and changing my lambda handler to `/opt/nodejs/node_modules/datadog-lambda-js/handler.handler` will handle tracing automatically for me.

## Actual Behavior

In the console I have this message
>Lambda can't find the file /opt/nodejs/node_modules/datadog-lambda-js/handler.js. Make sure that your handler upholds the format: file-name.method.

When I send a test event, some expected things happen:
- trace appears in APM
- `dd.trace_id` & `dd.span_id` appear in the logs and I can filter by them

However, the maximum memory limit is reached 100% of the time (128MB in this case).

## Steps to Reproduce the Problem

  1. Create a lambda with the DD layer
  1. Send a test event

This is the relevant portion of the terraform defining this function:

```terraform
resource "aws_lambda_function" "lambda-test" {
  function_name = "my-lambda-test"
  role          = var.iam_role.arn

  handler = "/opt/nodejs/node_modules/datadog-lambda-js/handler.handler"
  runtime = "nodejs12.x"
  timeout     = 60
  memory_size = 128

  environment {
    variables = merge(
      {
        DD_TRACE_ENABLED    = true,
        DD_API_KEY          = var.datadog_api_key
        DD_LAMBDA_HANDLER   = "src/index.handler",
        DD_LOG_LEVEL        = "debug",
        DD_LOGS_INJECTION   = true
        DD_FLUSH_TO_LOG     = true
        DD_ENHANCED_METRICS = false
      },
      var.environment_vars
    )
  }

  depends_on = [
    aws_cloudwatch_log_group.lambda_logs
  ]

  layers = ["arn:aws:lambda:eu-west-1:464622532012:layer:Datadog-Node12-x:24"]
}
```

## Specifications

  - Datadog Lambda Layer version: **arn:aws:lambda:eu-west-1:464622532012:layer:Datadog-Node12-x:24**
  - Node version: **Node.js 12.x**
  
## Stacktrace
  This is the log output from sending a test event.
  ```
  er.js:43:35)\n    
at Object.openSync (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:91:23)\n    
at Object.readFileSync (fs.js:360:35)\n    
at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:91:53\n    
at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:43:56",
"service":"my-test-lambda",
"component":"fs",
"span.kind":"internal",
"file.path":"/home/sbx_user1051/.aws/config",
"file.flag":"r"
},
"metrics":{"_sample_rate":1,"_sampling_priority_v1":1},
"start":1592414079831124000,
"duration":180420,
"service":"my-test-lambda-fs"
},{
"trace_id":"312ccbad2fe3fb80",
"span_id":"55dfc3d99a865658",
"parent_id":"0f603fb5c2d0e7ca",
"name":"fs.operation",
"resource":"readFileSync",
"error":0,
"meta":{
	"error.msg":"ENOENT: no such file or directory, open '/home/sbx_user1051/.aws/config'",
	"error.type":"Error",
	"error.stack":"Error: ENOENT: no such file or directory, open '/home/sbx_user1051/.aws/config'\n    
		at Object.openSync (fs.js:458:3)\n    
		at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:91:53\n    
		at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:43:56\n    
		at Scope._activate (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/scope/async_hooks.js:51:14)\n    
		at Scope.activate (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)\n    
		at DatadogTracer.trace (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:43:35)\n    
		at Object.openSync (/opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:91:23)\n    
		at Object.readFileSync (fs.js:360:35)\n    
		at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:91:53\n    
		at /opt/nodejs/node_modules/dd-trace/packages/dd-trace/src/tracer.js:43:56",
	"service":"my-test-lambda",
	"component":"fs",
	"span.kind":"internal",
	"file.path":"/home/sbx_user1051/.aws/config",
	"file.flag":"r"
},
"metrics":{"_sample_rate":1,"_sampling_priority_v1":1},
	"start":1592414079831086300,
	"duration":230469,
	"service":"my-test-lambda-fs"
},{
"trace_id":"312ccbad2fe3fb80",
"span_id":"34b6e0c824c62f0c",
"parent_id":"0f603fb5c2d0e7ca",
"name":"http.request",
"resource":"POST",
"error":0,
"meta":{
	"service":"my-test-lambda",
	"span.kind":"client","http.method":"POST",
	"http.url":"http://sqs.eu-west-1.amazonaws.com:443/",
	"http.status_code":"200"
},
"metrics":{"_sample_rate":1,"_sampling_priority_v1":1},
"start":1592414079831647700,
"duration":102364502,
"service":"my-test-lambda-http-client",
"type":"http"
},{
"trace_id":"312ccbad2fe3fb80",
"span_id":"0f603fb5c2d0e7ca",
"parent_id":"312ccbad2fe3fb80",
"name":"aws.request",
"resource":"sendMessageBatch https://sqs.eu-west-1.amazonaws.com/123456789012/development_my-test-lambda-data",
"error":0,
"meta":{
	"service":"my-test-lambda",
	"span.kind":"client",
	"aws.operation":"sendMessageBatch",
	"aws.region":"eu-west-1",
	"aws.service":"SQS",
	"component":"aws-sdk",
	"aws.response.request_id":"3079362f-3511-58ec-9f80-614b64aee5c3",
	"aws.sqs.queue_name":"https://sqs.eu-west-1.amazonaws.com/123456789012/development_my-test-lambda-data"
},
"metrics":{"_sample_rate":1,"_sampling_priority_v1":1},
"start":1592414079830559000,
"duration":104427246,
"service":"my-test-lambda-aws-sqs"
},{
"trace_id":"312ccbad2fe3fb80",
"span_id":"312ccbad2fe3fb80",
"parent_id":"0000000000000000",
"name":"aws.lambda",
"resource":"src/index.handler",
"error":0,
"meta":{
	"service":"my-test-lambda",
	"cold_start":"false",
	"function_arn":"arn:aws:lambda:eu-west-1:123456789012:function:my-test-lambda",
	"request_id":"db45a3f2-fd7b-40ea-809e-ac1981b4a54c",
	"resource_names":"my-test-lambda",
	"language":"javascript"
},
"metrics":{"_sample_rate":1,"_dd.agent_psr":1,"_sampling_priority_v1":1},
"start":1592414079790683100,
"duration":144564209,
"service":"my-test-lambda",
"type":"serverless"
}]]}
END RequestId: db45a3f2-fd7b-40ea-809e-ac1981b4a54c
REPORT RequestId: db45a3f2-fd7b-40ea-809e-ac1981b4a54c	Duration: 180.87 ms	Billed Duration: 200 ms	Memory Size: 128 MB	Max Memory Used: 128 MB	
  ```

**Comment by tianchu** [comment]
@MxKaras you can ignore this error message, which is from the editor not being able to open the handler.js for editing in the IDE. It is expected. I will update README to mention this.

> Lambda can't find the file /opt/nodejs/node_modules/datadog-lambda-js/handler.js. Make sure that your handler upholds the format: file-name.method.

It looks like your function is writing traces correctly into the log group. You need to install the [Datadog Forwarder](https://github.com/DataDog/datadog-serverless-functions/tree/master/aws/logs_monitoring#installation) (if you haven't) in order to relay the trace payloads from the logs to Datadog.

**Comment by MxKaras** [comment]
Thanks @tianchu . I think what really threw me was the memory limit being hit. Turns out that 128MB wasn't enough for the function with DD - went from ~87MB to ~150MB on each invocation!
